version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cinema